// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "String Literal",
    id: "53a78f5f-2904-4209-9a93-754ba487052d",
    method: "GET",
    address: "http://localhost:5095/String/ConcatenateByStringLiteral"
  });

  postman[Request]({
    name: "String Builder",
    id: "ec6fb8fe-4754-40b1-a4f7-2a437b62e6d1",
    method: "GET",
    address: "http://localhost:5095/String/ConcatenateByStringBuilder"
  });

  postman[Request]({
    name: "Serialisation Newtonsoft",
    id: "e0db5f74-c0aa-43d5-8a75-1ace8513ef6c",
    method: "GET",
    address: "http://localhost:5095/Serialisation/SerialiseWithNewtonsoft"
  });

  postman[Request]({
    name: "Serialisation Protobuf",
    id: "d07a5e22-b8c3-4c0d-b49e-841eb50a3f48",
    method: "GET",
    address: "http://localhost:5095/Serialisation/SerialiseWithProtobuf"
  });

  postman[Request]({
    name: "Mapping Manually",
    id: "6c8c911b-e982-4a49-b2f8-75b6aa47d72e",
    method: "GET",
    address: "http://localhost:5095/Mapping/MapManually"
  });

  postman[Request]({
    name: "Mapping Mapster Code Gen",
    id: "56b1ecb6-be3c-4244-b898-458a8d745a0c",
    method: "GET",
    address: "http://localhost:5095/Mapping/MapWithMapsterCodeGeneration"
  });

  postman[Request]({
    name: "Iterate Foreach",
    id: "2a5b13e0-febd-4ecb-b0b4-5bc4d148cb43",
    method: "GET",
    address: "http://localhost:5095/Iteration/IterateWithForEach"
  });

  postman[Request]({
    name: "Iterate Foreach Span",
    id: "5e40e614-8446-4819-9223-1d4c3935b390",
    method: "GET",
    address: "http://localhost:5095/Iteration/IterateWithSpan"
  });

  postman[Request]({
    name: "Full Stack Unoptimised",
    id: "50596435-89e8-4556-bad9-b6071ed1eeb2",
    method: "GET",
    address: "http://localhost:5095/FullStack/Unoptimised"
  });

  postman[Request]({
    name: "Full Stack Optimised",
    id: "b69f4ea7-cf72-44f1-b556-4d9a097147ec",
    method: "GET",
    address: "http://localhost:5095/FullStack/Optimised"
  });
}
